"""Generate a consolidated AutoScoring performance summary for professor review.

Inputs (already generated by evaluate.py + Docker):
  backend/data/evaluation/gsm8k_report.json
  backend/data/evaluation/asap_hw_report.json

Outputs:
  backend/data/evaluation/PERFORMANCE_SUMMARY.csv  — 1 row per dataset
  backend/data/evaluation/PERFORMANCE_README.txt   — human-readable report
"""
from __future__ import annotations

import csv
import json
from datetime import datetime
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DATA = BASE / "data" / "evaluation"

REPORTS = [
    ("GSM8K Math Word Problems (200 samples, 0-100 scale)",
     DATA / "gsm8k_report.json",
     "math"),
    ("ASAP Prompt 3 Handwritten (185 samples, 0-10 scale)",
     DATA / "asap_hw_report.json",
     "science (handwritten OCR)"),
]

METRIC_ORDER = [
    ("sample_count", "Samples (N)"),
    ("pearson_correlation", "Pearson r"),
    ("pearson_p_value", "Pearson p-value"),
    ("spearman_correlation", "Spearman ρ"),
    ("spearman_p_value", "Spearman p-value"),
    ("r_squared", "R²"),
    ("quadratic_weighted_kappa", "Quadratic Weighted Kappa"),
    ("mean_absolute_error", "MAE"),
    ("root_mean_squared_error", "RMSE"),
    ("mean_human_score", "Mean Human Score"),
    ("mean_system_score", "Mean System Score"),
    ("exact_match_rate", "Exact Match Rate"),
    ("within_1_point_rate", "Within ±1 Point"),
    ("within_2_point_rate", "Within ±2 Points"),
]

INTERPRETATION = {
    "pearson_correlation": (
        "LINEAR AGREEMENT between system and human scores. "
        "≥0.9 = excellent, ≥0.8 = very good, ≥0.7 = good, ≥0.5 = acceptable. "
        "p-value < 0.05 means the correlation is statistically significant."
    ),
    "spearman_correlation": (
        "RANK-ORDER AGREEMENT (robust to outliers and non-linear score scales). "
        "Similar thresholds to Pearson. Measures whether the system correctly "
        "'ranks' answers from worst to best the way a human would."
    ),
    "r_squared": (
        "VARIANCE EXPLAINED: what fraction of human score variance is captured "
        "by the system. ≥0.8 = very strong, ≥0.6 = strong. Complement (1-R²) "
        "is unexplained variance."
    ),
    "quadratic_weighted_kappa": (
        "QWK — STANDARD EDUCATIONAL AGREEMENT METRIC for automated scoring "
        "(ASAP AES benchmark, Kaggle competitions, etc.). Penalizes disagreements "
        "by the SQUARE of the grade distance, so being off by 3 points is 9× "
        "worse than being off by 1. ≥0.8 = excellent, ≥0.6 = substantial. "
        "This is the MOST IMPORTANT metric for a professor comparing to ASAP "
        "competition baselines."
    ),
    "mean_absolute_error": (
        "MAE — AVERAGE POINT ERROR between human and system score. "
        "Lower is better. Interpret using the scale: for 0-10 scale, MAE<1 "
        "means within a grade boundary on average; for 0-100, MAE<15 is good."
    ),
    "root_mean_squared_error": (
        "RMSE — penalizes LARGE errors quadratically. Always ≥MAE. "
        "If RMSE >> MAE it means a few answers are badly misgraded."
    ),
    "exact_match_rate": (
        "Fraction of samples where system score == human score exactly "
        "(after rounding). 15% is typical for continuous scoring."
    ),
    "within_1_point_rate": (
        "Fraction within ±1 point of the human score. "
        "≥70% = reliable classroom tool. For 0-100 scale interpret as ±1 pt out of 100."
    ),
    "within_2_point_rate": (
        "Fraction within ±2 points. ≥95% = very robust grading system."
    ),
}


def load_report(path: Path) -> dict | None:
    if not path.exists():
        return None
    with path.open() as f:
        return json.load(f)


def interpret_row(metrics: dict, dataset_name: str) -> list[str]:
    lines = [f"\n  {dataset_name}"]
    p = metrics["pearson_correlation"]
    k = metrics["quadratic_weighted_kappa"]
    w1 = metrics["within_1_point_rate"] * 100
    if p >= 0.9:
        lines.append("    ✅ Pearson r ≥ 0.90 — EXCELLENT linear agreement with human graders.")
    elif p >= 0.8:
        lines.append("    ✅ Pearson r ≥ 0.80 — VERY GOOD linear agreement.")
    elif p >= 0.7:
        lines.append("    🟢 Pearson r ≥ 0.70 — Good linear agreement.")
    else:
        lines.append(f"    ⚠️  Pearson r = {p:.2f}, below 0.70 target.")

    if k >= 0.8:
        lines.append("    ✅ QWK ≥ 0.80 — EXCELLENT inter-rater agreement (ASAP competition standard).")
    elif k >= 0.6:
        lines.append("    🟢 QWK ≥ 0.60 — SUBSTANTIAL inter-rater agreement.")
    else:
        lines.append(f"    ⚠️  QWK = {k:.2f}, below 0.60 substantial-agreement threshold.")

    if w1 >= 75:
        lines.append(f"    ✅ {w1:.1f}% of scores within ±1 point of human grade — classroom-ready.")
    elif w1 >= 60:
        lines.append(f"    🟢 {w1:.1f}% within ±1 point — acceptable with teacher review.")
    else:
        lines.append(f"    ⚠️  {w1:.1f}% within ±1 point, needs improvement.")
    return lines


def main() -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    rows_out = []
    header = ["Dataset", "Subject/Notes"] + [label for _, label in METRIC_ORDER]
    narrative_lines: list[str] = []

    for dataset_name, path, subject in REPORTS:
        rep = load_report(path)
        if rep is None:
            print(f"[SKIP] missing: {path}")
            continue
        m = rep["metrics"]
        row = [dataset_name, subject]
        for key, _label in METRIC_ORDER:
            val = m.get(key)
            if val is None:
                row.append("")
                continue
            if key.endswith("_rate") and isinstance(val, (int, float)):
                row.append(f"{val * 100:.2f}%")
            elif "p_value" in key and isinstance(val, (int, float)):
                row.append(f"{val:.4f}")
            elif isinstance(val, float):
                row.append(f"{val:.4f}")
            else:
                row.append(str(val))
        rows_out.append(row)
        narrative_lines.extend(interpret_row(m, dataset_name))

    csv_path = DATA / "PERFORMANCE_SUMMARY.csv"
    with csv_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows_out)
    print(f"Wrote {csv_path}")

    readme_lines = [
        "=" * 78,
        "  AutoScoring System — PERFORMANCE REPORT FOR PROFESSOR",
        f"  Generated: {timestamp}",
        "=" * 78,
        "",
        "1. WHAT THE SYSTEM DOES",
        "   AutoScoring combines a BERT sentence-embedding model",
        "   (sentence-transformers/all-MiniLM-L6-v2) with keyword and coherence",
        "   heuristics to grade short-answer responses. Scoring weights:",
        "       Semantic similarity  = 60%    (BERT cosine similarity)",
        "       Keyword coverage     = 25%    (stopword-free token overlap)",
        "       Coherence heuristic  = 15%    (length, sentences, repetitions)",
        "",
        "2. EVALUATION PROTOCOL",
        "   For every question, we run the model_answer vs student_answer through",
        "   the scorer, then compare the output score to a HUMAN-GIVEN reference.",
        "   Agreement is measured with 8 standard metrics used in the ASAP AES",
        "   short-answer grading competition.",
        "",
        "3. DATASETS EVALUATED",
    ]
    for name, _p, subj in REPORTS:
        readme_lines.append(f"   • {name}  [{subj}]")
    readme_lines += [
        "",
        "4. METRIC INTERPRETATION (show this column to the professor)",
        "-" * 78,
    ]
    for key, _label in METRIC_ORDER:
        if key not in INTERPRETATION:
            continue
        readme_lines.append(f"  {_label:<30s}  {INTERPRETATION[key]}")
    readme_lines += [
        "",
        "5. CONSOLIDATED SCORES",
        "-" * 78,
    ]
    readme_lines.append("  " + f"{'Dataset':<45s} {'Pearson':>8s} {'Spearman':>9s} {'R²':>7s} {'QWK':>7s} {'MAE':>7s} {'±1pt%':>7s}")
    for row in rows_out:
        name = row[0]
        col = dict(zip(header, row))
        readme_lines.append(
            "  " + f"{name[:43]:<45s} "
                  f"{col['Pearson r']:>8s} "
                  f"{col['Spearman ρ']:>9s} "
                  f"{col['R²']:>7s} "
                  f"{col['Quadratic Weighted Kappa']:>7s} "
                  f"{col['MAE']:>7s} "
                  f"{col['Within ±1 Point']:>7s}"
        )

    readme_lines += ["", "6. VERDICT / PROFESSOR SUMMARY", "-" * 78]
    readme_lines.extend(narrative_lines)
    readme_lines += [
        "",
        "7. HOW TO REPRODUCE (run inside Docker backend container)",
        "   $ docker exec fyp-backend-1 python evaluate.py \\\n"
        "        data/evaluation/gsm8k_eval.csv \\\n"
        "        --output /app/data/evaluation/gsm8k_report.json",
        "   $ docker exec fyp-backend-1 python evaluate.py \\\n"
        "        data/evaluation/asap_prompt3_handwritten.csv \\\n"
        "        --output /app/data/evaluation/asap_hw_report.json",
        "   Or re-run everything locally:",
        "   $ python backend/scripts/generate_performance_summary.py",
        "",
        "=" * 78,
        "  End of report",
        "=" * 78,
    ]

    readme_path = DATA / "PERFORMANCE_README.txt"
    readme_path.write_text("\n".join(readme_lines))
    print(f"Wrote {readme_path}")
    print("\n--- QUICK PREVIEW ---")
    print("\n".join(readme_lines[40:70]))


if __name__ == "__main__":
    main()
